### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by bitstarr** [jkphl/grunt-svg-sprite#84]
Hi,

With 1.4.0 i'm getting this error:
``
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Callback was already called.
``

1.3.7 works. Which information can I provide to help finding the bug?

**Comment by jkphl** [comment]
@bitstarr Sorry for the late reply. I'm a bit helpless, to be honest — the tests still run fine, and I'm not a Grunt user anymore, so I don't have any setup handy so that I could reproduce this problem. Could you please post your complete Gruntfile and the directory / file structure you're using?

**Comment by AlexDovnar** [comment]
Have the same problem with 'svg-sprite'

The command: 
`svg-sprite --symbol --symbol-inline --shape-id-generator=icon- --symbol-sprite=icons.svg --symbol-dest=./ --dest=public/images/svg-sprite/ resources/assets/svg/*.svg`

`(node:13154) UnhandledPromiseRejectionWarning: Error: Callback was already called.
   at /home/user/dev/apps/passport/node_modules/async/dist/async.js:966:32
   at /home/user/dev/apps/passport/node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:92:3
   at process._tickCallback (internal/process/next_tick.js:68:7)
   at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
   at startup (internal/bootstrap/node.js:238:19)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

(node:13154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:13154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by QuipHop** [comment]
Got the same with webpack
